[0m05:36:13.265683 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f138e247430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f138e985c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f138e985bb0>]}


============================== 05:36:13.267774 | a8072f26-140d-4a90-bfb3-114ce84f0dc4 ==============================
[0m05:36:13.267774 [info ] [MainThread]: Running with dbt=1.7.4
[0m05:36:13.268093 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init sample', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m05:36:13.268440 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/root/.dbt')}
[0m05:36:13.268636 [info ] [MainThread]: Creating dbt configuration folder at 
[0m05:36:13.269237 [debug] [MainThread]: Starter project path: /home/venvs/dbt/lib/python3.9/site-packages/dbt/include/starter_project
[0m05:36:13.274339 [info ] [MainThread]: 
Your new dbt project "sample" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m05:36:13.274635 [info ] [MainThread]: Setting up your profile.
[0m05:36:34.827028 [error] [MainThread]: Encountered an error:

[0m05:36:34.828560 [error] [MainThread]: Traceback (most recent call last):
  File "/home/venvs/dbt/lib/python3.9/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/venvs/dbt/lib/python3.9/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/venvs/dbt/lib/python3.9/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
  File "/home/venvs/dbt/lib/python3.9/site-packages/dbt/task/init.py", line 344, in run
    self.setup_profile(profile_name)
  File "/home/venvs/dbt/lib/python3.9/site-packages/dbt/task/init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/venvs/dbt/lib/python3.9/site-packages/dbt/task/init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/venvs/dbt/lib/python3.9/site-packages/dbt/task/init.py", line 165, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/home/venvs/dbt/lib/python3.9/site-packages/dbt/task/init.py", line 131, in generate_target_from_input
    target[key] = click.prompt(
  File "/home/venvs/dbt/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/home/venvs/dbt/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m05:36:34.829795 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 21.56931, "process_user_time": 1.0351, "process_kernel_time": 0.064069, "process_mem_max_rss": "95136", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m05:36:34.830464 [debug] [MainThread]: Command `dbt init` failed at 05:36:34.830309 after 21.57 seconds
[0m05:36:34.830895 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f138e247430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f138bb02d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f138bb02df0>]}
[0m05:36:34.831372 [debug] [MainThread]: Flushing usage events
[0m05:37:43.246592 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc6a14d430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc6a88bca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc6a88bc40>]}


============================== 05:37:43.248543 | 6a6cbc0c-4f10-4254-a73d-9f292babe59b ==============================
[0m05:37:43.248543 [info ] [MainThread]: Running with dbt=1.7.4
[0m05:37:43.248966 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init --profiles-dir . sample', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m05:37:43.249632 [info ] [MainThread]: A project called sample already exists here.
[0m05:37:43.250196 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.008459134, "process_user_time": 0.968715, "process_kernel_time": 0.040946, "process_mem_max_rss": "91008", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m05:37:43.250540 [debug] [MainThread]: Command `dbt init` succeeded at 05:37:43.250470 after 0.01 seconds
[0m05:37:43.250806 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc6a14d430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc6c592730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc67f9c0d0>]}
[0m05:37:43.251075 [debug] [MainThread]: Flushing usage events
